name-template: Beta Release
tag-template: beta
category-template: "### $TITLE"
exclude-labels:
  - technical
  - invalid
  - duplicate
categories:
  - title: New to Last Epoch Planner
    labels:
      - enhancement
  - title: Fixed Crashes
    labels:
      - crash
  - title: User Interface
    labels:
      - user-interface
  - title: Fixed Calculations
    labels:
      - "bug: calculation"
  - title: Fixed Behaviours
    labels:
      - "bug: behaviour"
  - title: Accuracy Improvements
    labels:
      - "bug: accuracy"
  - title: Fixed Bugs
    labels:
      - bug
  - title: Other changes
change-template: "* $TITLE by @$AUTHOR in https://github.com/Musholic/LastEpochPlanner/pull/$NUMBER"
template: |
  ## What’s Changed

  $CHANGES
  
  **Full Changelog**: https://github.com/Musholic/LastEpochPlanner/compare/$PREVIOUS_TAG...beta