name: Push beta branch
on: 
  workflow_run:
    workflows: ["Run Tests"]
    branches: [dev]
    types: [completed]
  workflow_dispatch:
jobs:
  push-beta:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set line endings
        run: git config --global core.autocrlf true
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'dev'
      - name: Configure bot user
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Add beta suffix to manifest version
        run: |
          sed -i 's/<Version number="\([^"]*\)"/<Version number="\1-beta"/' manifest.xml
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Release notes
        run: >
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token;
          gh release view beta | tee temp_change.md
      - name: Tweak changelogs
        run: |
          sed -i 's/\r$//' .github/tweak_changelogs.sh
          chmod +x .github/tweak_changelogs.sh
          .github/tweak_changelogs.sh beta
      - name: Update manifest.xml
        run: python3 update_manifest.py --quiet --in-place
      - name: Push to beta branch
        run: |
            git commit -am "Beta release" --allow-empty --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
            git push origin HEAD:beta --force
