name: Sync Release to Master

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  sync-release-to-master:
    # Checks that the push to dev was from a pull request whose head branch started with 'release-'.
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Merge fast-forward dev into master
        run: |
          git merge ${{ github.sha }} --ff-only
          git push

      - name: Publish release
        run: |
          VERSION=$(echo ${{ github.head_ref }} | sed 's/release-//')
          gh release edit v$VERSION --draft=false
